import { WeeklySchedule } from './types';

const createTask = (
  title: string,
  category: 'Review Class' | 'Problem Sets' | 'Meals' | 'Rest/Sleep' | 'Exams' | 'Other',
  startTime: string,
  endTime: string,
  notes: string = ''
) => ({
  id: crypto.randomUUID(),
  title,
  category,
  startTime,
  endTime,
  status: 'pending' as const,
  notes,
});

export const initialSchedule: WeeklySchedule = {
  Monday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:30', 'Consistent sleep is key for memory consolidation.'),
    createTask('Breakfast', 'Meals', '07:30', '08:00', 'Start the day with a healthy meal.'),
    createTask('Deep Work - Problem Sets', 'Problem Sets', '08:00', '09:30', 'Tackle challenging problems with a fresh mind.'),
    createTask('Micro-break', 'Rest/Sleep', '09:30', '09:50', 'Short break to stretch and reset.'),
    createTask('Review Class', 'Review Class', '10:00', '13:00', 'Fixed schedule. Focus on active listening.'),
    createTask('Lunch + recharge', 'Meals', '13:30', '14:30', 'A proper, mindful break away from your desk.'),
    createTask('Problem Sets / Worked Examples', 'Problem Sets', '14:30', '16:30', 'Apply concepts from the morning review.'),
    createTask('Break + snack', 'Rest/Sleep', '16:30', '17:00', 'A short break to recharge.'),
    createTask('Topic Consolidation & Notes', 'Problem Sets', '17:00', '19:00', 'Review and organize your notes from the day.'),
    createTask('Dinner', 'Meals', '19:00', '20:00'),
    createTask('Adaptive Study Block', 'Problem Sets', '20:00', '22:00', 'Flexible time to revisit difficult topics or continue with problem sets.'),
    createTask('Wind-down stretch + log progress', 'Rest/Sleep', '22:00', '22:30', 'Relax your mind and body before sleep.'),
    createTask('Sleep', 'Rest/Sleep', '23:00', '23:59', 'Aim for 7-8 hours of quality sleep.')
  ],
  Tuesday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:30'),
    createTask('Breakfast', 'Meals', '07:30', '08:00'),
    createTask('Deep Work - Problem Sets', 'Problem Sets', '08:00', '09:30'),
    createTask('Micro-break', 'Rest/Sleep', '09:30', '09:50'),
    createTask('Review Class', 'Review Class', '10:00', '13:00'),
    createTask('Lunch + recharge', 'Meals', '13:30', '14:30'),
    createTask('Problem Sets / Worked Examples', 'Problem Sets', '14:30', '16:30'),
    createTask('Break + snack', 'Rest/Sleep', '16:30', '17:00'),
    createTask('Topic Consolidation & Notes', 'Problem Sets', '17:00', '19:00'),
    createTask('Dinner', 'Meals', '19:00', '20:00'),
    createTask('Adaptive Study Block', 'Problem Sets', '20:00', '22:00'),
    createTask('Wind-down stretch + log progress', 'Rest/Sleep', '22:00', '22:30'),
    createTask('Sleep', 'Rest/Sleep', '23:00', '23:59')
  ],
  Wednesday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:30'),
    createTask('Breakfast', 'Meals', '07:30', '08:00'),
    createTask('Deep Work - Problem Sets', 'Problem Sets', '08:00', '09:30'),
    createTask('Micro-break', 'Rest/Sleep', '09:30', '09:50'),
    createTask('Review Class', 'Review Class', '10:00', '13:00'),
    createTask('Lunch + recharge', 'Meals', '13:30', '14:30'),
    createTask('Problem Sets / Worked Examples', 'Problem Sets', '14:30', '16:30'),
    createTask('Break + snack', 'Rest/Sleep', '16:30', '17:00'),
    createTask('Topic Consolidation & Notes', 'Problem Sets', '17:00', '19:00'),
    createTask('Dinner', 'Meals', '19:00', '20:00'),
    createTask('Adaptive Study Block', 'Problem Sets', '20:00', '22:00'),
    createTask('Wind-down stretch + log progress', 'Rest/Sleep', '22:00', '22:30'),
    createTask('Sleep', 'Rest/Sleep', '23:00', '23:59')
  ],
  Thursday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:30'),
    createTask('Breakfast', 'Meals', '07:30', '08:00'),
    createTask('Deep Work - Problem Sets', 'Problem Sets', '08:00', '09:30'),
    createTask('Micro-break', 'Rest/Sleep', '09:30', '09:50'),
    createTask('Review Class', 'Review Class', '10:00', '13:00'),
    createTask('Lunch + recharge', 'Meals', '13:30', '14:30'),
    createTask('Problem Sets / Worked Examples', 'Problem Sets', '14:30', '16:30'),
    createTask('Break + snack', 'Rest/Sleep', '16:30', '17:00'),
    createTask('Topic Consolidation & Notes', 'Problem Sets', '17:00', '19:00'),
    createTask('Dinner', 'Meals', '19:00', '20:00'),
    createTask('Adaptive Study Block', 'Problem Sets', '20:00', '22:00'),
    createTask('Wind-down stretch + log progress', 'Rest/Sleep', '22:00', '22:30'),
    createTask('Sleep', 'Rest/Sleep', '23:00', '23:59')
  ],
  Friday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:30'),
    createTask('Breakfast', 'Meals', '07:30', '08:00'),
    createTask('Deep Work - Problem Sets', 'Problem Sets', '08:00', '09:30'),
    createTask('Micro-break', 'Rest/Sleep', '09:30', '09:50'),
    createTask('Targeted Review & Mock Recall', 'Exams', '10:00', '13:00', 'Focus on weak areas and practice with mock questions.'),
    createTask('Lunch + recharge', 'Meals', '13:30', '14:30'),
    createTask('Problem Sets / Weak Area Drills', 'Problem Sets', '14:30', '16:30', 'Drill down into topics you find challenging.'),
    createTask('Break + snack', 'Rest/Sleep', '16:30', '17:00'),
    createTask('Formula Sheet & Notes Consolidation', 'Other', '17:00', '19:00', 'Finalize your notes and formula sheets for the exam.'),
    createTask('Dinner', 'Meals', '19:00', '20:00'),
    createTask('Full Review - Recall & Mini-Quiz', 'Exams', '20:00', '22:00', 'A final review session to boost confidence.'),
    createTask('Wind-down stretch + log progress', 'Rest/Sleep', '22:00', '22:30'),
    createTask('Sleep', 'Rest/Sleep', '23:00', '23:59')
  ],
  Saturday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:30'),
    createTask('Light breakfast', 'Meals', '07:30', '08:00', 'Energy-rich but light meal.'),
    createTask('Flashcard review', 'Exams', '08:00', '09:30', 'Quick review of key concepts.'),
    createTask('Micro-break', 'Rest/Sleep', '09:30', '09:50'),
    createTask('Exam Prep / Exam', 'Exams', '10:00', '13:00', 'The main event. Good luck!'),
    createTask('Post-exam lunch', 'Meals', '13:30', '14:30'),
    createTask('Rest / decompression', 'Rest/Sleep', '14:30', '16:30', 'Relax and unwind after the exam.'),
    createTask('Break', 'Rest/Sleep', '16:30', '17:00'),
    createTask('Light walk / unwind', 'Rest/Sleep', '17:00', '19:00', 'Gentle activity to clear your head.'),
    createTask('Dinner', 'Meals', '19:00', '20:00'),
    createTask('Light review if needed', 'Other', '20:00', '22:00', 'Optional: a brief look at any confusing topics from the exam.'),
    createTask('Relax', 'Rest/Sleep', '22:00', '22:30'),
    createTask('Sleep early', 'Rest/Sleep', '23:00', '23:59')
  ],
  Sunday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:30'),
    createTask('Brunch', 'Meals', '08:00', '09:30'),
    createTask('Light review (flashcards, formulas)', 'Other', '09:30', '10:00', 'A quick, low-stress review.'),
    createTask('Break', 'Rest/Sleep', '10:00', '11:00'),
    createTask('Active recovery', 'Rest/Sleep', '11:00', '13:30', 'Engage in a hobby or light physical activity.'),
    createTask('Lunch', 'Meals', '13:30', '14:30'),
    createTask('Active recovery / exercise', 'Rest/Sleep', '14:30', '16:30'),
    createTask('Break', 'Rest/Sleep', '16:30', '17:00'),
    createTask('Planning session', 'Other', '17:00', '19:00', 'Plan the week ahead to set yourself up for success.'),
    createTask('Dinner', 'Meals', '19:00', '20:00'),
    createTask('Light read-through only', 'Other', '20:00', '22:00', 'Casual reading, no intense studying.'),
    createTask('Relax', 'Rest/Sleep', '22:00', '22:30'),
    createTask('Sleep early', 'Rest/Sleep', '23:00', '23:59')
  ],
};
