import { WeeklySchedule } from './types';

const createTask = (
  title: string,
  category: 'Review Class' | 'Problem Sets' | 'Meals' | 'Rest/Sleep' | 'Exams' | 'Other',
  startTime: string,
  endTime: string,
  notes: string = ''
) => ({
  id: crypto.randomUUID(),
  title,
  category,
  startTime,
  endTime,
  status: 'pending' as const,
  notes,
});

export const initialSchedule: WeeklySchedule = {
  Monday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:00', 'Aim for 7-8 hours of quality sleep.'),
    createTask('Morning Routine & Breakfast', 'Meals', '07:00', '08:00', 'Hydrate and have a good breakfast.'),
    createTask('Deep Work: Problem Set A', 'Problem Sets', '08:00', '09:30', 'Tackle fresh problems with a clear mind. Use Pomodoro (25 min on, 5 min off).'),
    createTask('Short Break', 'Rest/Sleep', '09:30', '10:00', 'Stretch, walk, or relax before class.'),
    createTask('Review Class', 'Review Class', '10:00', '13:00', 'Fixed schedule. Focus on active listening.'),
    createTask('Lunch', 'Meals', '13:00', '14:00', 'A proper, mindful break. Step away from your desk.'),
    createTask('Review Class', 'Review Class', '14:00', '17:00', 'Second session. Stay engaged.'),
    createTask('Decompress & Light Exercise', 'Rest/Sleep', '17:00', '18:00', 'Short walk or stretching to clear your head after class.'),
    createTask('Dinner', 'Meals', '18:00', '19:00'),
    createTask('Problem Set B', 'Problem Sets', '19:00', '21:00', 'Continue with assigned problem sets.'),
    createTask('Wind Down', 'Rest/Sleep', '21:00', '22:00', 'No screens. Read, listen to music, or meditate.'),
    createTask('Sleep', 'Rest/Sleep', '22:00', '23:59', 'Consistent sleep is key for memory consolidation.'),
  ],
  Tuesday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:00'),
    createTask('Morning Routine & Breakfast', 'Meals', '07:00', '08:00'),
    createTask('Deep Work: Problem Set C', 'Problem Sets', '08:00', '09:30', 'Focus on a new set of problems.'),
    createTask('Short Break', 'Rest/Sleep', '09:30', '10:00'),
    createTask('Review Class', 'Review Class', '10:00', '13:00', 'Fixed schedule.'),
    createTask('Lunch', 'Meals', '13:00', '14:00'),
    createTask('Review Class', 'Review Class', '14:00', '17:00', 'Fixed schedule.'),
    createTask('Decompress & Light Exercise', 'Rest/Sleep', '17:00', '18:00'),
    createTask('Dinner', 'Meals', '18:00', '19:00'),
    createTask('Problem Set D', 'Problem Sets', '19:00', '21:00'),
    createTask('Wind Down', 'Rest/Sleep', '21:00', '22:00'),
    createTask('Sleep', 'Rest/Sleep', '22:00', '23:59'),
  ],
  Wednesday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:00'),
    createTask('Morning Routine & Breakfast', 'Meals', '07:00', '08:00'),
    createTask('Deep Work: Problem Set E', 'Problem Sets', '08:00', '09:30'),
    createTask('Short Break', 'Rest/Sleep', '09:30', '10:00'),
    createTask('Review Class', 'Review Class', '10:00', '13:00', 'Fixed schedule.'),
    createTask('Lunch', 'Meals', '13:00', '14:00'),
    createTask('Review Class', 'Review Class', '14:00', '17:00', 'Fixed schedule.'),
    createTask('Decompress & Light Exercise', 'Rest/Sleep', '17:00', '18:00'),
    createTask('Dinner', 'Meals', '18:00', '19:00'),
    createTask('Problem Set F', 'Problem Sets', '19:00', '21:00', 'Aim to finish the bulk of weekly problems today.'),
    createTask('Wind Down', 'Rest/Sleep', '21:00', '22:00'),
    createTask('Sleep', 'Rest/Sleep', '22:00', '23:59'),
  ],
  Thursday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:00'),
    createTask('Morning Routine & Breakfast', 'Meals', '07:00', '08:00'),
    createTask('Problem Set Catch-up/Review', 'Problem Sets', '08:00', '09:30', 'Finish any remaining problems or review challenging ones.'),
    createTask('Short Break', 'Rest/Sleep', '09:30', '10:00'),
    createTask('Review Class', 'Review Class', '10:00', '13:00', 'Fixed schedule.'),
    createTask('Lunch', 'Meals', '13:00', '14:00'),
    createTask('Review Class', 'Review Class', '14:00', '17:00', 'Fixed schedule.'),
    createTask('Decompress & Light Exercise', 'Rest/Sleep', '17:00', '18:00'),
    createTask('Dinner', 'Meals', '18:00', '19:00'),
    createTask('Active Recall & Weak Areas', 'Problem Sets', '19:00', '21:00', 'Review notes from the week. Identify topics you struggled with.'),
    createTask('Wind Down', 'Rest/Sleep', '21:00', '22:00'),
    createTask('Sleep', 'Rest/Sleep', '22:00', '23:59'),
  ],
  Friday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:00'),
    createTask('Morning Routine & Breakfast', 'Meals', '07:00', '08:00'),
    createTask('Targeted Review - Weak Area 1', 'Problem Sets', '08:00', '09:30', 'Focus on one key weak area identified yesterday.'),
    createTask('Short Break', 'Rest/Sleep', '09:30', '10:00'),
    createTask('Review Class', 'Review Class', '10:00', '13:00', 'Final class of the week.'),
    createTask('Lunch', 'Meals', '13:00', '14:00'),
    createTask('Review Class', 'Review Class', '14:00', '17:00', 'Final class of the week.'),
    createTask('Light Review & Prep', 'Problem Sets', '17:00', '18:00', 'Organize notes for tomorrow\'s exam. No heavy studying.'),
    createTask('Dinner', 'Meals', '18:00', '19:00'),
    createTask('Total Rest - No Studying', 'Rest/Sleep', '19:00', '21:00', 'Your brain needs to rest before the exam. Relax completely.'),
    createTask('Wind Down', 'Rest/Sleep', '21:00', '22:00'),
    createTask('Sleep', 'Rest/Sleep', '22:00', '23:59', 'Aim for a full 8 hours before the exam.'),
  ],
  Saturday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '07:00'),
    createTask('Exam Day Breakfast', 'Meals', '07:00', '08:00', 'Light, but energy-rich breakfast.'),
    createTask('Pre-Exam Warmup', 'Exams', '08:00', '09:00', 'Quick formula review. No new problems.'),
    createTask('Main Exam', 'Exams', '09:00', '18:00', 'This is a large block to accommodate your exam schedule. Adjust as needed.'),
    createTask('Dinner', 'Meals', '18:00', '19:00'),
    createTask('Post-Exam Unwind', 'Rest/Sleep', '19:00', '22:00', 'Completely disconnect. You\'ve earned it.'),
    createTask('Sleep', 'Rest/Sleep', '22:00', '23:59'),
  ],
  Sunday: [
    createTask('Sleep', 'Rest/Sleep', '00:00', '08:00', 'Sleep in a bit.'),
    createTask('Leisurely Breakfast', 'Meals', '08:00', '09:00'),
    createTask('Recharge Activity', 'Rest/Sleep', '09:00', '12:00', 'Hobby, walk in nature, or anything you enjoy.'),
    createTask('Lunch', 'Meals', '12:00', '13:00'),
    createTask('Light Review & Planning', 'Problem Sets', '13:00', '15:00', 'Briefly review last week\'s exam results (if available) and plan the upcoming week. Keep it short.'),
    createTask('Total Rest & Recreation', 'Rest/Sleep', '15:00', '18:00', 'Free time.'),
    createTask('Dinner', 'Meals', '18:00', '19:00'),
    createTask('Relax & Prepare for Week', 'Rest/Sleep', '19:00', '21:00', 'Relax, lay out clothes for Monday, etc.'),
    createTask('Wind Down', 'Rest/Sleep', '21:00', '22:00'),
    createTask('Sleep', 'Rest/Sleep', '22:00', '23:59', 'Get to bed on time to start the week strong.'),
  ],
};
